# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93efb7f8b133f026303adbac6c35691b6005a0705156d5e714f64e2eb341c788d0b3a3aebcaaa0adc191b8fcfcb631c11647cc0a9d87caead1475f4bd0fb7447

test:
  secret_key_base: 6c0d27ded2cea9ae6f68f02aeb8470f54e70da350074c50a375599e037bfc7d84fed3a9176f86cd3ec89370f3025562a33aff753a7e168a5fcf9121f97fee891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
